services:
  elasticsearch:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 5368709120 # 5GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    depends_on:
      - kibana

  kibana:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    image: docker.elastic.co/kibana/kibana:8.15.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  init-pipeline:
    image: curlimages/curl
    depends_on:
      - elasticsearch
    volumes:
      - ./docker/init-pipeline.sh:/usr/local/bin/init-pipeline.sh  # .shファイルをコンテナ内にコピー
    entrypoint: ["sh", "/usr/local/bin/init-pipeline.sh"]  # .shファイルを実行

  filebeat:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    image: docker.elastic.co/beats/filebeat:8.15.1
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/log:ro # ログファイルのマウント
    depends_on:
      - init-pipeline

volumes:
  es-data:
    driver: local